'root':
- changed-files:
  - any-glob-to-any-file: ["**"]

'physical':
- changed-files:
  - any-glob-to-any-file: ['mithril/framework/physical/**/*']

'logical models':
- changed-files:
  - any-glob-to-any-file: ['mithril/framework/models/*']

