'root':
- changed-files:
  - any-glob-to-any-file: ["**"]

'Physical':
- changed-files:
  - any-glob-to-any-file: ['mithril/framework/physical/**/*']

'Models':
- changed-files:
  - any-glob-to-any-file: ['mithril/models/**/*', 'mithril/framework/logical/essential_primitives.py']

'Logical':
- changed-files:
  - any-glob-to-any-file: ['mithril/framework/logical/base.py', 'mithril/framework/logical/model.py', 'mithril/framework/logical/primitive.py']

'Backend':
- changed-files:
  - any-glob-to-any-file: ['mithril/framework/backends/**/*']

'Tests':
- changed-files:
  - any-glob-to-any-file: ['tests/**/*]

'Examples':
- changed-files:
  - any-glob-to-any-file: ['examples/**/*]

'Codegen':
- changed-files:
  - any-glob-to-any-file: ['mithril/framework/codegen/**/*]

'Constraints':
- changed-files:
  - any-glob-to-any-file: ['mithril/framework/constraints.py]

'Benchmarks':
- changed-files:
  - any-glob-to-any-file: ['benchmarks/**/*']

'Utils':
- changed-files:
  - any-glob-to-any-file: ['mithril/utils/**/*']

'Framework Utils':
- changed-files:
  - any-glob-to-any-file: ['mithril/framework/utils.py']

'Common':
- changed-files:
  - any-glob-to-any-file: ['mithril/framework/common.py']
