name: Assigner
on:
  workflow_run:
    workflows: ["Pull Request Labeler"]
    types: 
      - completed

jobs:
  assign-labels:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: print all labels    
      run: |
       x=${{ toJson(github.event.pull_request.labels.*.name) }}
       echo $x

    - name: deploy        
      if: contains(github.event.pull_request.labels.*.name, 'root')      
      run: |
        gh pr edit --add-assignee mehmetozsoy1
      
