name: Assign Reviewers Based on Labels

on:
  pull_request:
    types: [labeled]


jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
    - name: Check which label was applied
      id: label_check
      if: ${{ github.event.label.name == 'physical' }}
      run: gh pr review --add-reviews mehmetozsoy1

