name: Assign Reviewers Based on Labels

on:
  pull_request:
    types: [labeled]


jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Check which label was applied
      id: label_check
      if: ${{ github.event.label.name == 'physical' }}
      run: gh pr edit --add-assignee mehmetozsoy1

