name: CI
on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Make compile script executable
        run: chmod +x ./mithril/backends/with_manualgrad/c_backend/src/compile.sh
      - name: Compile C code
        run: |
          pushd ./mithril/backends/with_manualgrad/c_backend/src
          ./compile.sh
          popd
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install torch==2.4.1 --index-url https://download.pytorch.org/whl/cpu
          pip install --upgrade "jax[cpu]"
          pip install -r requirements/dev.txt
      - name: Execute testcase unit tests
        run: pytest --cov --cov-report=xml -s tests/
      - name: Upload coverage reports to Codecov
        run: |
          # Replace `linux` below with the appropriate OS
          # Options are `alpine`, `linux`, `macos`, `windows`
          curl -Os https://cli.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov --verbose upload-process --fail-on-error -t ${{ secrets.CODECOV_TOKEN }} -n 'service'-${{ github.run_id }} -F service -f coverage-service.xml  
