name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true

    - name: Check which label was applied
      id: label_check
      run: echo "label=${{ github.event.label.name }}" >> $GITHUB_ENV
      
    - name: Assign reviewer based on label
      if: env.label == 'root'
      run: |
        gh pr edit --add-assignee mehmetozsoy1





