name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true

  assign-labels:
    needs: labeler
    runs-on: ubuntu-latest
    steps:
    - name: print all labels    
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh workflow run asigner.yml

    - name: deploy        
      if: contains(github.event.pull_request.labels.*.name, 'root')      
      run: |
        gh pr edit --add-assignee mehmetozsoy1
