name: Pull Request Labeler
on:
- pull_request_target

jobs:
  labeler:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: actions/labeler@v5
    - id: labeler
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
    - id: assign_people
      if: contains(steps.labeler.outputs.all-labels, 'physical')
      run: |
        gh pr edit --add-assignee mehmetozsoy1
